#! /bin/zsh
# Note the trailing jq -s . "slurps" the stream of entities into an array


/usr/local/bin/yabai -m query --spaces | \
  /usr/local/bin/jq '.[]' | \
  /usr/local/bin/jq '{label: .label, id: .id, index: .index}' | \
  /usr/local/bin/jq '{uid: .id, title: ((.index|tostring) + " - " + .label), subtitle: .index, arg: .index}' | \
  /usr/local/bin/jq -s . |\
  /usr/local/bin/jq '{items: .}'

